# Generated by Django 5.2.1 on 2025-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moodstat_rename_insights_insight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodstat',
            name='percentSurprise',
        ),
        migrations.AddField(
            model_name='journal',
            name='lastProcessedContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
